name:                mlatu
version:             0.1.0.0
github:              "brightly-salty/haskell"
author:              "Caden Haustein"
maintainer:          "code@brightlysalty.33mail.com"
copyright:           "2021 Caden Haustein"

extra-source-files:
- ../README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mlatu-lang/libraries#readme>

default-extensions:
- NoImplicitPrelude
- LambdaCase
- TupleSections
- MultiWayIf
- TypeOperators
- BlockArguments
- NumericUnderscores
- OverloadedStrings
- ViewPatterns
- PatternSynonyms
- ExplicitForAll
- TypeApplications
- ScopedTypeVariables
- RankNTypes
- LiberalTypeSynonyms
- NamedFieldPuns
- RecordWildCards
- FlexibleInstances
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- GeneralizedNewtypeDeriving
- InstanceSigs
- ConstrainedClassMethods
- MultiParamTypeClasses
- FunctionalDependencies
- DeriveGeneric
- NoStarIsType
- ImportQualifiedPost

dependencies:
- base >= 4.7 && < 5
- protolude 
- megaparsec
- containers

library:
  source-dirs: src

tests:
  haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mlatu
    - hspec
